name: Deploy to WP Engine
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest  
    steps: 
    - uses: actions/checkout@v2
    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@feature/exclude 
      with:

      # Deploy vars 
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }} 
        CACHE_CLEAR: TRUE
        FLAGS: -azvr --inplace --delete --exclude-from "/github/workspace/deployignore"
        
      
      # Branches & Environments 
        PRD_BRANCH: main
        PRD_ENV: selive