name: Deploy to WP Engine
on:
  push:

env:
  PRD_BRANCH: main
  PRD_ENV: selive

  STG_BRANCH: stage
  STG_ENV: selivestaging

  DEV_BRANCH: dev
  DEV_ENV: sedemodev

  WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPENGINE_SSH_KEY_PRIVATE }} 
  TPO_SRC_PATH: ""
  TPO_PATH: ""

  PHP_LINT: true
  PHP_VER: "7.4"

jobs:
  build:
    runs-on: ubuntu-latest  
    steps: 
    - uses: actions/checkout@v2
    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@feature/stage
