name: Deploy to WP Engine
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest  
    steps: 
    - uses: actions/checkout@v2
    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@feature/exclude
      with:

      # Keys, lint & url options 
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
        FLAGS: -azvr --inplace --delete --exclude '.*' --exclude 'wp-content/uploads' 
        CACHE_CLEAR: FALSE 
      
      # Branches & Environments 
        PRD_BRANCH: main
        PRD_ENV: selive