name: Deploy to WP Engine
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest  
    steps: 
    - uses: actions/checkout@v2
    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@stage/cleanup 
      with:

      # Deploy vars 
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }} 
        PHP_LINT: TRUE
        FLAGS: -azvr --inplace --delete --exclude=".*"
        CACHE_CLEAR: TRUE
        TPO_SRC_PATH: "wp-content/themes/authority-pro/"
        TPO_PATH: "wp-content/themes/authority-pro/"
        
      
      # Branches & Environments 
        PRD_BRANCH: main
        PRD_ENV: selive