name: Deploy to WP Engine
  
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps: 
    - name: Deploy to WP Engine 
    - uses: bowiedev/github-action-wpengine-ssh-deploy@master
    - env: 
          WPE_ENV_NAME: selive
          WPENGINE_SSHG_KEY_PUBLIC: ${{ secrets.WPENGINE_SSHG_KEY_PUBLIC }}
          WPENGINE_SSHG_KEY_PRIVATE: ${{ secrets.WPENGINE_SSHG_KEY_PRIVATE }}
